#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Thu Mar 30 18:27:52 CST 2017
# Module: ssh
# Submodule: 
# Command: keygen
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function run() {

  if [ "${arg3}" != "" ] && [ $(echo "${arg3}" | grep "@" | wc -l) != 0 ]; then
    email=${arg3}
  fi

  if [ "${email}" == "" ]; then
    email="$(whoami)@$(hostname)"
  fi

  cli="ssh-keygen -t rsa -b 4096 -C ${email}"

  ${cli}

  result=$?

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
